---
name: Checks
 
on: [push]
 
jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose up -d && docker-compose run --rm app sh -c "python manage.py test"
        # run: docker-compose up -d && docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
